libdrm chanes to support rpl-s platform
intel/external-libdrm pull request #28
Opened 2022-12-15 14:35 UTC by bkothapx

Tracked-On: OAM-105280
Signed-off-by: kalle <kalyan.alle@intel.com>
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>

2023-01-13 06:13 UTC, bkothapx commented
Reviewers: @hongyu.zhang@intel.com  @yu.y.chen@intel.com @hongcheng.xie@intel.com  @jeevaka.badrappan@intel.com; @qiming.shi@intel.com @shyjumon.n@intel.com

2023-01-13 06:31 UTC, bkothapx commented
Reviewers: @zhy1030 @hongcheng-xie @JeevakaPrabu @shyjumon-n

2023-01-17 08:29 UTC, feijiang1 approved these changes

2023-01-17 08:35 UTC, JeevakaPrabu requested changes

2023-01-17 08:35 UTC, JeevakaPrabu commented on intel/intel_chipset.c
> +	INTEL_RPLS_IDS(12),
RPL is 13th generation. Could you please check and correct the generation information mapping for all platforms?

2023-01-17 08:38 UTC, JeevakaPrabu approved these changes

2023-01-18 10:31 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/264

2023-01-18 10:42 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/265

2023-01-19 05:05 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/266

2023-02-10 06:55 UTC, feijiang1 approved these changes

2023-02-10 07:03 UTC, shyjumon-n approved these changes
LGTM

2023-02-10 07:29 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckEpic Bad Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/305

2023-02-10 13:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/308

2023-02-13 09:53 UTC, shyjumon-n approved these changes
LGTM

2023-02-13 09:55 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/309

2023-02-13 14:52 UTC, feijiang1 approved these changes

2023-02-13 19:29 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/310

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-02-13 20:03 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/179

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-02-13 22:27 UTC, merged

2023-02-13 22:28 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/139