Add support for RPLP
intel/external-libdrm pull request #29
Opened 2022-12-28 05:07 UTC by prashanth-intel

Add RPLP platform support and PCIIDs

Tracked-On: OAM-103696
Signed-off-by: Suresh, Prashanth <prashanth.suresh@intel.com>

2023-02-01 07:11 UTC, rajucm2007 approved these changes

2023-02-01 08:02 UTC, JeevakaPrabu requested changes

2023-02-01 08:02 UTC, JeevakaPrabu commented on xf86drm.h
why is this specific to RPL support?

2023-02-06 05:43 UTC, prashanth-intel commented on xf86drm.h
These changes are not specific to RPL. But more of an improvement. 
Changes are taken from: https://github.com/intel-innersource/os.linux.yocto.build.meta-intel-iot-main/pull/256/files

2023-02-06 15:57 UTC, JeevakaPrabu approved these changes

2023-02-07 04:55 UTC, feijiang1 approved these changes
LGTM

2023-02-07 09:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/283

2023-02-07 09:45 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/284

2023-02-07 10:01 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/286

2023-02-07 10:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/287

2023-02-07 11:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/290

2023-02-07 14:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/291

2023-02-07 14:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/292

2023-02-08 04:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/293

2023-02-08 06:16 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_sriov) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/294

2023-02-08 06:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/296

2023-02-08 14:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/299

2023-02-08 17:52 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/297

Done by "Suresh, Prashanth" <prashanth.suresh@intel.com>

2023-02-08 18:29 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/174

Done by "Suresh, Prashanth" <prashanth.suresh@intel.com>

2023-02-08 21:03 UTC, merged

2023-02-08 21:05 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Suresh, Prashanth" <prashanth.suresh@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/134